classdef mFSMv1 < Snake.AbstractFSM
    %MFSMV1 the multiple empty space coverage automatons
    
	properties
		memory_map;
		direction_map;
    end	
    
    methods(Static)
        function [bits_in_memory] = GetBits()
            bits_in_memory = 2;
        end
    end
    
	methods
		function obj = mFSMv1()
            error('Do not use this version. Collisions are possible.'); 
			do_nothing = Snake.AbstractFSM.do_nothing;
			Error = Snake.AbstractFSM.Error;
			Stop = Snake.AbstractFSM.Stop;
			% agent decision	
			go_north = Snake.AbstractFSM.go_north; go_east = Snake.AbstractFSM.go_east; 
			go_south = Snake.AbstractFSM.go_south; go_west = Snake.AbstractFSM.go_west;
			
			obj.memory_map = Error * ones(2 ^ Rain.mFSMv1.GetBits(), 2 ^ Snake.AbstractFSM.num_readings, 9);
			obj.direction_map = Error * ones(2 ^ Rain.mFSMv1.GetBits(), 2 ^ Snake.AbstractFSM.num_readings, 9);

            obj.memory_map(:, 1:4, 1) = [ ...
                0, 2, 1, 2; ...
                1, Error, Error, Error; ...
                2, 2, 2, 2; ...
                Error, Error, Error, Error];
            obj.memory_map(:, 1:4, 2) = [ ...
                0, 2, 3, 2; ...
                1, 1, 3, 3; ...
                0, 2, 1, 1; ...
                0, 3, 2, 2];
            obj.memory_map(:, 1:4, 3) = [ ...
                0, 1, 1, 1; ...
                1, 2, 2, 2; ...
                2, 1, 3, 3; ...
                3, 3, 2, 2];
            obj.memory_map(:, 1:4, 4) = [ ...
                0, 1, 0, 1; ...
                1, 2, 1, 2; ...
                2, 3, 2, 3; ...
                3, 2, 3, 2];
            obj.memory_map(:, 1:8, 5) = [ ...
                0, 2, 3, 1, 2, 2, 3, 2; ...
                1, 1, 3, 1, 3, 1, 3, 3; ...
                2, 2, 1, 2, 1, 2, 1, 1; ...
                0, 3, 2, 3, 2, 3, 2, 2];
            obj.memory_map(:, 1:8, 6) = [ ...
                0, 2, 0, 1, 2, 2, 1, 2; ...
                1, 2, 1, 2, 2, 2, 2, 2; ...
                2, 2, 2, 3, 2, 3, 3, 3; ...
                3, 3, 3, 2, 3, 2, 2, 2];
            obj.memory_map(:, 1:8, 7) = [ ...
                0, 1, 1, 0, 1, 1, 1, 1; ...
                0, 2, 2, 1, 2, 2, 2, 2; ...
                2, 1, 3, 2, 1, 1, 3, 1; ...
                3, 1, 2, 3, 1, 1, 2, 1];
            obj.memory_map(:, 1:8, 8) = [ ...
                0, 2, 1, 0, 2, 2, 1, 2; ...
                1, 2, 2, 1, 2, 2, 2, 2; ...
                2, 2, 3, 2, 3, 2, 3, 3; ...
                3, 3, 2, 3, 2, 3, 2, 2];
            obj.memory_map(:, 1:4, 9) = [ ...
                0, 2, 1, 2; ...
                1, 2, 2, 2; ...
                2, 2, 3, 3; ...
                3, 3, 2, 2];

            obj.direction_map(:, 1:4, 1) = [ ...
                do_nothing, go_north, go_west, go_north; ...
                do_nothing, Error, Error, Error; ...
                do_nothing, do_nothing, do_nothing, do_nothing; ...
                Error, Error, Error, Error];
            obj.direction_map(:, 1:4, 2) = [ ...
                do_nothing, go_north, do_nothing, go_north; ...
                do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, do_nothing, go_east, go_east; ...
                do_nothing, do_nothing, do_nothing, do_nothing];
            obj.direction_map(:, 1:4, 3) = [ ...
                do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, go_east, go_south, go_south; ...
                do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, do_nothing, go_south, go_south];
            obj.direction_map(:, 1:4, 4) = [ ...
                do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing,   go_south, do_nothing,   go_south; ...
                do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing,   go_south, do_nothing,   go_south];
            obj.direction_map(:, 1:8, 5) = [ ...
                do_nothing, go_north, do_nothing, go_west, go_north, go_north, do_nothing, go_north; ...
                do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, do_nothing, go_east, do_nothing, go_east, do_nothing, go_east, go_east; ...
                do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing];
            obj.direction_map(:, 1:8, 6) = [ ...
                do_nothing, go_north, do_nothing, do_nothing, go_north, go_north, do_nothing, go_north; ...
                do_nothing, go_north, do_nothing, go_south, go_north, go_north, go_south, go_north; ...
                do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, do_nothing, do_nothing, go_south, do_nothing, go_south, go_south, go_south];
            obj.direction_map(:, 1:8, 7) = [ ...
                do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, go_east, go_south, do_nothing, go_south, go_east, go_south, go_south; ...
                do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, do_nothing, go_south, do_nothing, do_nothing, do_nothing, go_south, do_nothing];
            obj.direction_map(:, 1:8, 8) = [ ...
                do_nothing, go_north, do_nothing, do_nothing, go_north, go_north, do_nothing, go_north; ...
                do_nothing, go_north, go_south, do_nothing, go_north, go_north, go_south, go_north; ...
                do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, do_nothing, go_south, do_nothing, go_south, do_nothing, go_south, go_south];
            obj.direction_map(:, 1:4, 9) = [ ...
                do_nothing, go_north, do_nothing, go_north; ...
                do_nothing, go_north, go_south, go_north; ...
                do_nothing, do_nothing, do_nothing, do_nothing; ...
                do_nothing, do_nothing, go_south, go_south];
		end
		
		function [result_memory_map] = GetMemoryMap(this)
			result_memory_map = this.memory_map;
		end

		function [result_direction_map] = GetDirectionMap(this)
			result_direction_map = this.direction_map;
		end

	end
end

