classdef StateMachine < Cylinders.StateMachine.TimerStateMachine
    %STATEMACHINE Actual Implementation of Sorting algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS ! [Need to check]
    %
    % Based on covering algorithm Ver 9
    % This is a SORTING algorithm for 1's [EXITING vehicles]
    %
    % Ver = 301 (1 for exiting, 2 for continuing)
    %
    % 2 bit timer [LSB bits] - 00 and 01 are times at which COVERING algo is executed; 10 is the Pos 9 exiting vehicles moving  east; 11 - Pos 8
    % continuing vehicles moving west
    % 2 bit state : non-MSB bit - is the state bit for COVERING algo; both bits used at Pos 8 by continuing vehicles to count empty spaces moving up
    % in the one-to-last column (Pos 9). At the secong empty cell passing up - you are allowed to move West
    
    properties (Constant)
        MasksVersion = 20200829;
        TimerBits = 2;
        ValueBits = 2;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            main_direction = 0;
            north_9_north_5 = 1;
            empty_cell_not_passed = 0;
            empty_cell_passed = 1;
            empty_cell_passed_back = 2;
            empty_cell_passed_twice = 3;
            

            %% here comes position 1
            % please check that readings are [west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                     }}, ...
                } ...                
            );
            
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[empty, agent], { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty, empty], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[empty, empty, agent], { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[empty, agent, empty], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[empty, agent, agent], { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, empty, agent], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_east), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, agent, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                } ...                
            );
        end
    end
end

