classdef StateMachine < Cylinders.StateMachine.TimerStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    %
    % one conceptual bit of time parity (to prevent possible collisions in next pair NW vs SE) and one of direction up/down
    % 1 is the bit value to move north in 5,9; 0 - to move south and west
    % The huge difference vs ver 7: is that poisition 1 will now take time to enter position 5 
    % This should fix the problem with 3 row grids (and (2, m-1) stuck forever
    
    properties (Constant)
        MasksVersion = 20200407;
        TimerBits = 1;
        ValueBits = 1;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            main_direction = 0;
            north_9_north_5 = 1;
            

            %% here comes position 1
            % please check that readings are [west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {empty, { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                     }}, ...
                    {agent,	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                } ...                
            );
            
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                     }}, ...
                    {[empty, agent], { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                     }}, ...
                    {[agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.stateMachine{currentPosition - 4};
            %% here comes position 9
            % please check that readings are [north, south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                     }}, ...
                    {[empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                     }}, ...
                    {[agent, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                } ...                
            );
        end
    end
end

