classdef StateMachine < Cylinders.StateMachine.SparseStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    %
    % two bits are tracking the state
    % one bit is for row parity (learned)
    % one bit is for column parity (learned)
    % one bit is for tracking current (even dimension. row, then column) parity
    
    properties (Constant)
        MasksVersion = 20220424;
        TimerBits = 0;
        ValueBits = 5;
    end

    properties (Constant, Access = private)
        StateInitial = 0;
        StateRowParity = 1;
        StateColParity = 2;
        StateRun = 3;
    end
    
    methods (Access = private, Static)
        % bit_values(1) - state
        % bit_values(2) - row_parity
        % bit_values(3) - col_parity
        % bit_values(4) - cur_parity
        function [memory] = ExpandMemory(bit_values)
            memory  = bitshift(bit_values(1), 3) + bitshift(bit_values(2), 2) + bitshift(bit_values(3), 1) + bitshift(bit_values(4), 0);
        end
        
        function [memory] = NextState(bit_values)
            memory = Cylinders.StateMachine.Ver108.StateMachine.ExpandMemory(bit_values + [1, 0, 0, 0]);
        end
        
        function [memory] = FlipParity(bit_values)
            memory = Cylinders.StateMachine.Ver108.StateMachine.ExpandMemory([bit_values(1), ...
                (bit_values(1) == Cylinders.StateMachine.Ver108.StateMachine.StateRowParity) * (1 - bit_values(2)) + (bit_values(1) ~= Cylinders.StateMachine.Ver108.StateMachine.StateRowParity) * bit_values(2), ...
                (bit_values(1) == Cylinders.StateMachine.Ver108.StateMachine.StateColParity) * (1 - bit_values(3)) + (bit_values(1) ~= Cylinders.StateMachine.Ver108.StateMachine.StateColParity) * bit_values(3), ...
                (bit_values(1) == Cylinders.StateMachine.Ver108.StateMachine.StateRun) * (1 - bit_values(4)) + (bit_values(1) ~= Cylinders.StateMachine.Ver108.StateMachine.StateRun) * bit_values(4) ...
                ]);
        end
    end
    
    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            wall = Cylinders.Visibility.Constants.Wall;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            even = 0;
            odd = 1;
            

            %% here comes position 1
            % please check that readings are [north, west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty], { ... 
                                        {[this.StateInitial, even, even, even], { @this.ExpandMemory,    go_west }}, ...
                                        {[this.StateRun, even, even, even],     { @this.ExpandMemory,    go_west }}, ...
                                        {[this.StateRun, even,  odd, even],     { @this.ExpandMemory,    go_west }}, ...
                                        {[this.StateRun,  odd, even, even],     { @this.FlipParity,      go_west }}, ...
                                     }}, ...
                } ...                
            );
            
            %% here comes position 2
            % please check that readings are [north, east]
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.NextState,    go_north }}, ...
                                        {[this.StateRun,        even, even, even], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.ExpandMemory, go_north }}, ...
                                     }}, ...
                } ...                
            );
        
            %% here comes position 3
            % please check that readings are [east, south]
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRowParity,	even, even, even], { @this.NextState,    go_east }}, ...
                                        {[this.StateRowParity,	 odd, even, even], { @this.NextState,    go_east }}, ...
                                        {[this.StateRun,        even, even,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,        even,  odd,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.FlipParity,   go_east }}, ...
                                     }}, ...
                } ...                
            );
        
            %% here comes position 4
            % please check that readings are [south, west]
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateColParity,	even, even, even], { @this.NextState,    go_south }}, ...
                                        {[this.StateColParity,	even,  odd, even], { @this.NextState,    go_south }}, ...
                                        {[this.StateColParity,   odd, even, even], { @this.NextState,    go_south }}, ...
                                        {[this.StateColParity,   odd,  odd, even], { @this.ExpandMemory, do_nothing }}, ...
                                        {[this.StateRun,        even, even,  odd], { @this.FlipParity,   go_south }}, ...
                                        {[this.StateRun,        even,  odd,  odd], { @this.FlipParity,   go_south }}, ...
                                        {[this.StateRun,         odd, even, even], { @this.ExpandMemory, go_south }}, ...
                                     }}, ...
                } ...                
            );
        
            %% here comes position 5
            % please check that readings are [north, east, west]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even, even, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,         odd, even, even], { @this.FlipParity,   go_west }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.ExpandMemory, go_north }}, ...
                                        }}, ...
                } ...                
            );
        
            %% here comes position 6
            % please check that readings are [north, east, south]
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRowParity,  even, even, even], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRowParity,   odd, even, even], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRun,        even, even, even], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRun,        even, even,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRun,        even,  odd,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.ExpandMemory, go_north }}, ...
                                        }}, ...
                } ...                
            );
        
            %% here comes position 7
            % please check that readings are [east, south, west]
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateColParity,  even, even, even], { @this.FlipParity,   go_east }}, ...
                                        {[this.StateColParity,  even,  odd, even], { @this.FlipParity,   go_east }}, ...
                                        {[this.StateColParity,   odd, even, even], { @this.FlipParity,   go_east }}, ...
                                        {[this.StateColParity,   odd,  odd, even], { @this.FlipParity,   go_east }}, ...
                                        {[this.StateRun,        even, even,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,        even,  odd,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,         odd, even, even], { @this.FlipParity,   go_east }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.FlipParity,   go_east }}, ...
                                        }}, ...
                } ...                
            );
        
            %% here comes position 8
            % please check that readings are [north, south, west]
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRun,        even, even, even], { @this.FlipParity,   go_south }}, ...
                                        {[this.StateRun,        even, even,  odd], { @this.FlipParity,   go_south }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.FlipParity,   go_south }}, ...
                                        {[this.StateRun,        even,  odd,  odd], { @this.FlipParity,   go_south }}, ...
                                        {[this.StateRun,         odd, even, even], { @this.ExpandMemory, go_south }}, ...
                                        }}, ...
                } ...                
            );
            
            %% here comes position 9
            % please check that readings are [north, north_north, east, east_east, south, west]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, @this.ExpandMemory, ...
                { ...
                    {[empty, empty, empty, empty, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRun,        even, even, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even, even,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even,  odd,  odd], { @this.ExpandMemory, go_east }}, ...
                                        {[this.StateRun,         odd, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.ExpandMemory, go_north }}, ...
                                        }}, ...
                    {[empty, empty, empty, wall, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRun,        even, even, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even, even,  odd], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even,  odd,  odd], { @this.FlipParity,   go_north }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.ExpandMemory, go_north }}, ...
                                        }}, ...
                    {[empty, wall, empty, empty, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRun,        even, even, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,         odd, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.FlipParity,   go_west }}, ...
                                        }}, ...
                    {[empty, wall, empty, wall, empty, empty], { ... 
                                        {[this.StateInitial,    even, even, even], { @this.ExpandMemory, go_south }}, ...
                                        {[this.StateRun,        even, even, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,        even,  odd, even], { @this.ExpandMemory, go_west }}, ...
                                        {[this.StateRun,         odd, even,  odd], { @this.FlipParity,   go_west }}, ...
                                        }}, ...
                } ...                
            );
        end
    end
end

