classdef FSMv102 < Snake.AbstractFSM
	%FSMV102 The stoppable 1-bit distributed version 101
	
	properties
		memory_map;
		direction_map;
	end
	
    methods(Static)
        function [bits_in_memory] = GetBits()
            bits_in_memory = 1;
        end
    end
    
	methods
		function obj = FSMv102(~)
			Error = Snake.AbstractFSM.Error;
			do_nothing = Snake.AbstractFSM.do_nothing;
			Stop = Snake.AbstractFSM.Stop;
			% agent decision	
			go_north = Snake.AbstractFSM.go_north; go_east = Snake.AbstractFSM.go_east; 
			go_south = Snake.AbstractFSM.go_south; go_west = Snake.AbstractFSM.go_west;
			
			obj.memory_map = Error * ones(2 ^ Snake.FSMv102.GetBits(), 4, 9); % 5 is when no input is given
			obj.direction_map = Error * ones(2 ^ Snake.FSMv102.GetBits(), 4, 9);

			obj.memory_map(:, :, 1) = [ ...
					0, Error, Error, 1; ...
					Error, Error, Error, 0]; 
			obj.memory_map(:, :, 2) = [ ...
					1, 0, Error, Error; ...
					Error, Error, Error, Error];
			obj.memory_map(:, :, 3) = [ ...
					Error, 1, 0, Error; ...
					Error, 1, 1, Error];
			obj.memory_map(:, :, 4) = [ ...
					Error, Error, 0, 0; ...
					Error, Error, 1, 1];
			obj.memory_map(:, :, 5) = [ ...
					1, 0, Error, 1; ...
					1, Error, Error, 0];
			obj.memory_map(:, :, 6) = [ ...
					0, 0, 0, Error; ...
					1, 1, 1, Error];
			obj.memory_map(:, :, 7) = [ ...
					Error, 0, 0, 0; ...
					Error, 1, 1, 1];
			obj.memory_map(:, :, 8) = [ ...
					0, Error, 0, 0; ...
					1, Error, 1, 1];
			obj.memory_map(:, :, 9) = [ ...
					1, 0, 0, 0; ...
					1, 0, 1, 0];

			obj.direction_map(:, :, 1) = [ ...
					do_nothing, Error, Error, do_nothing; ...
					Error, Error, Error, go_west];
			obj.direction_map(:, :, 2) = [ ...
					go_north, do_nothing, Error, Error; ...
					Error, Error, Error, Error];
			obj.direction_map(:, :, 3) = [ ...
					Error, go_east, do_nothing, Error; ...
					Error, Stop, do_nothing, Error];
			obj.direction_map(:, :, 4) = [ ...
					Error, Error, go_south, do_nothing; ...
					Error, Error, Stop, do_nothing];
			obj.direction_map(:, :, 5) = [ ...
					do_nothing, do_nothing, Error, do_nothing; ...
					go_north, Error, Error, go_west];
			obj.direction_map(:, :, 6) = [ ...
					go_north, do_nothing, do_nothing, Error; ...
					Stop, do_nothing, do_nothing, Error];
			obj.direction_map(:, :, 7) = [ ...
					Error, go_east, do_nothing, do_nothing; ...
					Error, Stop, do_nothing, do_nothing];
			obj.direction_map(:, :, 8) = [ ...
					do_nothing, Error, go_south, do_nothing; ...
					do_nothing, Error, Stop, do_nothing];
			obj.direction_map(:, :, 9) = [ ...
					do_nothing, do_nothing, go_south, do_nothing; ...
					go_north, do_nothing, do_nothing, do_nothing];
		end
		
		function [result_memory_map] = GetMemoryMap(this)
			result_memory_map = this.memory_map;
		end

		function [result_direction_map] = GetDirectionMap(this)
			result_direction_map = this.direction_map;
		end

	end
	
end

