classdef FSMv5 < Snake.AbstractFSM
	%FSMV5 Summary of this class goes here
	%   Detailed explanation goes here
	
	properties
		memory_map;
		direction_map;
	end
	
    methods(Static)
        function [bits_in_memory] = GetBits()
            bits_in_memory = 2;
        end
    end
    
	methods
		function obj = FSMv5(~)
			Error = Snake.AbstractFSM.Error;
			do_nothing = Snake.AbstractFSM.do_nothing;
			Stop = Snake.AbstractFSM.Stop;
			% agent decision	
			go_north = Snake.AbstractFSM.go_north; go_east = Snake.AbstractFSM.go_east; 
			go_south = Snake.AbstractFSM.go_south; go_west = Snake.AbstractFSM.go_west;
			
			obj.memory_map = Error * ones(2 ^ Snake.FSMv5.GetBits(), 4, 9); % 5 is when no input is given
			obj.direction_map = Error * ones(2 ^ Snake.FSMv5.GetBits(), 4, 9);

			obj.memory_map(:, :, 1) = [ ...
				2, Error, Error, 0; ...
				Error, Error, Error, Error; ...
				Error, Error, Error, 3; ...
				3, Error, Error, 3];
			obj.memory_map(:, :, 2) = [ ...
				0, 1, Error, Error; ...
				2, 2, Error, Error; ...
				3, 3, Error, Error; ...
				3, 1, Error, Error];
			obj.memory_map(:, :, 3) = [ ...
				Error, 1, 1, Error; ...
				Error, 2, 2, Error; ...
				Error, 3, 3, Error; ...
				Error, 3, 3, Error];
			obj.memory_map(:, :, 4) = [ ...
				Error, Error, 2, 0; ...
				Error, Error, 2, Error; ...
				Error, Error, 3, Error; ...
				Error, Error, Error, 3];
			obj.memory_map(:, :, 5) = [ ...
				0, 1, Error, 0; ...
				2, 2, Error, 2; ...
				3, 2, Error, 3; ...
				3, 1, Error, 3];
			obj.memory_map(:, :, 6) = [ ...
				0, 2, 1, Error; ...
				2, 2, 2, Error; ...
				3, 2, 3, Error; ...
				3, Error, 3, Error];
			obj.memory_map(:, :, 7) = [ ...
				Error, 1, 1, 0; ...
				Error, 2, 2, 1; ...
				Error, 3, 3, 2; ...
				Error, Error, 3, 3];
			obj.memory_map(:, :, 8) = [ ...
				1, Error, 2, 0; ...
				Error, Error, 2, Error; ...
				Error, Error, 3, Error; ...
				3, Error, Error, 3];
			obj.memory_map(:, :, 9) = [ ...
				0, 2, 1, 0; ...
				2, 2, 2, 1; ...
				3, 2, 3, 2; ...
				3, Error, 3, 3];

			obj.direction_map(:, :, 1) = [ ...
				go_north, Error, Error, go_west; ...
				Error, Error, Error, Error; ...
				Error, Error, Error, do_nothing; ...
				do_nothing, Error, Error, do_nothing];
			obj.direction_map(:, :, 2) = [ ...
				go_north, do_nothing, Error, Error; ...
				do_nothing, do_nothing, Error, Error; ...
				Stop, go_east, Error, Error; ...
				do_nothing, do_nothing, Error, Error];
			obj.direction_map(:, :, 3) = [ ...
				Error, do_nothing, do_nothing, Error; ...
				Error, do_nothing, do_nothing, Error; ...
				Error, go_east, Stop, Error; ...
				Error, go_east, do_nothing, Error];
			obj.direction_map(:, :, 4) = [ ...
				Error, Error, do_nothing, do_nothing; ...
				Error, Error, do_nothing, Error; ...
				Error, Error, go_south, Error; ...
				Error, Error, Error, do_nothing];
			obj.direction_map(:, :, 5) = [ ...
				go_north, do_nothing, Error, go_west; ...
				do_nothing, do_nothing, Error, do_nothing; ...
				go_north, go_east, Error, do_nothing; ...
				do_nothing, do_nothing, Error, do_nothing];
			obj.direction_map(:, :, 6) = [ ...
				go_north, do_nothing, do_nothing, Error; ...
				do_nothing, do_nothing, do_nothing, Error; ...
				go_north, do_nothing, go_south, Error; ...
				do_nothing, Error, do_nothing, Error];
			obj.direction_map(:, :, 7) = [ ...
				Error, do_nothing, do_nothing, do_nothing; ...
				Error, do_nothing, do_nothing, do_nothing; ...
				Error, go_east, go_south, do_nothing; ...
				Error, Error, do_nothing, do_nothing];
			obj.direction_map(:, :, 8) = [ ...
				go_north, Error, do_nothing, do_nothing; ...
				Error, Error, do_nothing, Error; ...
				Error, Error, go_south, Error; ...
				do_nothing, Error, Error, do_nothing];
			obj.direction_map(:, :, 9) = [ ...
				go_north, do_nothing, do_nothing, do_nothing; ...
				do_nothing, do_nothing, do_nothing, do_nothing; ...
				go_north, do_nothing, go_south, do_nothing; ...
				do_nothing, Error, do_nothing, do_nothing];
		end
		
		function [result_memory_map] = GetMemoryMap(this)
			result_memory_map = this.memory_map;
		end

		function [result_direction_map] = GetDirectionMap(this)
			result_direction_map = this.direction_map;
		end

	end
	
end

