classdef StateMachine < Cylinders.StateMachine.GenericStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    %
    % three bits are used to  make a totally (rotational) symmetric 
    % traversal algorithm [with full traversal even in edge rows]
    
    properties (Constant)
        MasksVersion = 20200610;
        TimerBits = 0;
        ValueBits = 3;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            south_traverse_north = 0;
            south_traverse_south = 1;
            east_traverse_west = 2;
            east_traverse_east = 3;
            north_traverse_south = 4;
            north_traverse_north = 5;
            west_traverse_east = 6;
            west_traverse_west = 7;
            error_direction = 8;
            

            %% here comes position 1
            % please check that readings are [north]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty, { ... 
                                    Cylinders.StateMachine.Action(south_traverse_north, go_north), ...
                                    Cylinders.StateMachine.Action(east_traverse_west, go_west), ...
                                    Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                    Cylinders.StateMachine.Action(east_traverse_west, go_north), ...
                                    Cylinders.StateMachine.Action(north_traverse_north, go_north), ...
                                    Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                    Cylinders.StateMachine.Action(west_traverse_west, go_west), ...
                                    Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                 }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(south_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(south_traverse_north, go_east), ...
                                        Cylinders.StateMachine.Action(east_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(south_traverse_north, go_north), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(south_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(east_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_south), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(south_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(east_traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_west), ...
                                        Cylinders.StateMachine.Action(west_traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(south_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(south_traverse_north, go_east), ...
                                        Cylinders.StateMachine.Action(east_traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(east_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(north_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(west_traverse_west, go_west), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(south_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(south_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(east_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(north_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_south), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(south_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(east_traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(east_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_west), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(west_traverse_west, go_west), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(south_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(south_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(east_traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(east_traverse_west, go_north), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(north_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(west_traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(error_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ...
                                        Cylinders.StateMachine.Action(south_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(south_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(east_traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(east_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(north_traverse_south, go_south), ...
                                        Cylinders.StateMachine.Action(north_traverse_north, go_north), ...
                                        Cylinders.StateMachine.Action(west_traverse_east, go_east), ...
                                        Cylinders.StateMachine.Action(west_traverse_west, go_west), ...
                                     }}, ...
                } ...                
            );
        end
    end
    
    methods
        function [ignorable_states] = GetIgnorableStates(this)
            error_direction = 8;
            ignorable_states = [error_direction];
        end        
    end
end

