version = 319;
NO_VALUE = Print.TablePrinter.NO_VALUE;
% I you need to print agent type, then probably next line is a hint
% INCLUDE_TYPE = Print.TablePrinter.INCLUDE_TYPE;

content = { ...
    % check out position, type, 3 neighborhods, then 5 states
    % neighborhood is basicly a triple (type, position, neighborhood id)
    %%%%%
    1, 'E', {1, 1, 2}, {1, 1, 1}, NO_VALUE, 3, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, NO_VALUE, 7, {}, {}, {}, {}; ...
    %%%%%
    4, 'E', {1, 4, 2}, {1, 4, 1}, NO_VALUE, 2, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, NO_VALUE, 6, {}, {}, {}, {}; ...
    %%%%%
    8, 'E', {1, 8, 4}, {1, 8, 3}, {1, 8, 3}, 2, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, {}, 6, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {1, 8, 1}, 2, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {}, 6, {}, {}, {}, {}; ...
    %%%
    {}, {}, {1, 8, 2}, {1, 8, 3}, NO_VALUE, 2, 0, 1, 1, 'S'; ...
    {}, {}, {}, {}, {}, 6, {}, {}, {}, {}; ...
    {}, {}, {}, {1, 8, 1}, NO_VALUE, 2, 'N', NO_VALUE, NO_VALUE, NO_VALUE; ...
    {}, {}, {}, {}, {}, 6, {}, NO_VALUE, NO_VALUE, NO_VALUE; ...
    %%%
    {}, {}, {1, 8, 4}, {1, 8, 2}, NO_VALUE, 3, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, {}, 7, {}, {}, {}, {}; ...
    %%% IMPOSSIBLE
    %{}, {}, {1, 8, 3}, {1, 8, 2}, NO_VALUE, 3, 1, 1, 1, 'N'; ...
    %{}, {}, {}, {}, {}, 7, {}, {}, {}, {}; ...
    %{}, {}, {}, {1, 8, 1}, NO_VALUE, 3, {}, {}, 'S', NO_VALUE; ...
    %{}, {}, {}, {}, {}, 7, {}, {}, {}, NO_VALUE; ...
    };

printer = Print.TablePrinter();
printer.Print('Lemma.No.Stalls', version, 1, content);

content = { ...
    % check out position, type, 3 neighborhods, then 5 states
    % neighborhood is basicly a triple (type, position, neighborhood id)
    %%%%%
    1, 'C', {2, 1, 4}, {2, 1, 2}, NO_VALUE, 3, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, NO_VALUE, 7, {}, {}, {}, {}; ...
    %%%%%
    4, 'C', {2, 4, 4}, {2, 4, 2}, NO_VALUE, 2, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, NO_VALUE, 6, {}, {}, {}, {}; ...
    %%%%%
    8, 'C', {2, 8, 8}, {2, 8, 6}, {2, 8, 6}, 2, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, {}, 6, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {2, 8, 2}, 2, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {}, 6, {}, {}, {}, {}; ...
    %%%
    {}, {}, {2, 8, 4}, {2, 8, 6}, NO_VALUE, 2, 0, 1, 1, 'S'; ...
    {}, {}, {}, {}, {}, 6, {}, {}, {}, {}; ...
    {}, {}, {}, {2, 8, 2}, NO_VALUE, 2, 'N', NO_VALUE, NO_VALUE, NO_VALUE; ...
    {}, {}, {}, {}, {}, 6, {}, NO_VALUE, NO_VALUE, NO_VALUE; ...
    %%%
    {}, {}, {2, 8, 8}, {2, 8, 4}, NO_VALUE, 3, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, {}, 7, {}, {}, {}, {}; ...
    %%% also impossible
    %{}, {}, {2, 8, 6}, {2, 8, 4}, NO_VALUE, 3, 1, 1, 1, 'N'; ...
    %{}, {}, {}, {}, {}, 7, {}, {}, {}, {}; ...
    %{}, {}, {}, {2, 8, 2}, NO_VALUE, 3, {}, {}, 'S', NO_VALUE; ...
    %{}, {}, {}, {}, {}, 7, {}, {}, {}, NO_VALUE; ...
    };

printer = Print.TablePrinter();
printer.Print('Lemma.No.Stalls', version, 2, content);

content = { ...
    % check out position, type, 3 neighborhods, then 5 states
    % neighborhood is basicly a triple (type, position, neighborhood id)
    %%%%%
    2, 'E', {1, 2, 4}, {1, 2, 2}, NO_VALUE, 0, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, NO_VALUE, 4, {}, {}, {}, {}; ...
    %%%%%
    3, 'E', {1, 3, 4}, {1, 3, 3}, NO_VALUE, 1, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, NO_VALUE, 5, {}, {}, {}, {}; ...
    %%%%%
    6, 'E', {1, 6, 8}, {1, 6, 4}, {1, 6, 4}, 0, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, {}, 4, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {1, 6, 3}, 0, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {}, 4, {}, {}, {}, {}; ...
    %%%
    {}, {}, {1, 6, 7}, {1, 6, 4}, NO_VALUE, 0, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, {}, 4, {}, {}, {}, {}; ...
    {}, {}, {}, {1, 6, 3}, NO_VALUE, 0, 'S', NO_VALUE, NO_VALUE, NO_VALUE; ...
    {}, {}, {}, {}, {}, 4, {}, NO_VALUE, NO_VALUE, NO_VALUE; ...
    %%%
    {}, {}, {1, 6, 8}, {1, 6, 7}, NO_VALUE, 1, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, {}, 5, {}, {}, {}, {}; ...
    %%% also impossible
    };

printer = Print.TablePrinter();
printer.Print('Lemma.No.Stalls', version, 3, content);

content = { ...
    % check out position, type, 3 neighborhods, then 5 states
    % neighborhood is basicly a triple (type, position, neighborhood id)
    %%%%%
    2, 'C', {2, 2, 2}, {2, 2, 1}, NO_VALUE, 0, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, NO_VALUE, 4, {}, {}, {}, {}; ...
    %%%%%
    3, 'C', {2, 3, 2}, {2, 3, 1}, NO_VALUE, 1, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, NO_VALUE, 5, {}, {}, {}, {}; ...
    %%%%%
    6, 'C', {2, 6, 4}, {2, 6, 2}, {2, 6, 2}, 0, 0, 0, 0, 'N'; ...
    {}, {}, {}, {}, {}, 4, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {2, 6, 1}, 0, {}, {}, {}, {}; ...
    {}, {}, {}, {}, {}, 4, {}, {}, {}, {}; ...
    %%%
    {}, {}, {2, 6, 3}, {2, 6, 2}, NO_VALUE, 0, 1, 0, 0, 'N'; ...
    {}, {}, {}, {}, {}, 4, {}, {}, {}, {}; ...
    {}, {}, {}, {2, 6, 1}, NO_VALUE, 0, 'S', NO_VALUE, NO_VALUE, NO_VALUE; ...
    {}, {}, {}, {}, {}, 4, {}, NO_VALUE, NO_VALUE, NO_VALUE; ...
    %%%
    {}, {}, {2, 6, 4}, {2, 6, 3}, NO_VALUE, 1, 1, 1, 1, 'S'; ...
    {}, {}, {}, {}, {}, 5, {}, {}, {}, {}; ...
    %%% also impossible
    };

printer = Print.TablePrinter();
printer.Print('Lemma.No.Stalls', version, 4, content);

