close all;

data_dir = '../C++/Algorithm310xSeries/Algorithm310xSeries/Data/';
algoversion = 319; %#ok<NASGU>
printToLatex = true;

%DrawGraphs_m_mm(21);
% DrawGraphs_m((3:5)');
% DrawGraphs_m((16)');

 DrawGraphs_k([11]);
% DrawGraphs_k([1;7;10]);
% DrawGraphs_n_on_k([2]);
% DrawGraphs_ones((3:4)', 2, 0, 1);
% DrawGraphs_ones((8:9)', 2, 0, 1);
% DrawGraphs_ones(20, 1, 0, 2);
% DrawGraphs_FreeRoad_m((11:12)');
% DrawGraphs_FreeRoad_n_on_k((5:6)');

%DrawGraphs_Algos((15)');
%DrawGraphs_ones(19, 1, 6, 1);

function [] = DrawGraphs_Common(tests, algoversion, data_dir, mv, sv, skip, printToLatex, xLabelName, titleFcn, ...
    normPlotLegLocation, logPlotLegLocation, opt_IgnoreFirst, opt_drawRegressionLine, opt_drawLogRegression, ...
    opt_RegressionDegree, opt_TexFilenameSuffix, opt_try_experimental_bound, opt_drawMinMaxPoints, ...
    opt_secondaryReversed, opt_ignoreEdgeValues, opt_ignoreThreshold)

%% input parameters handling
    if(nargin < 12)
        opt_IgnoreFirst = 0;
    end
    if(nargin < 13)
        opt_drawRegressionLine = false;
    end
    if(nargin < 14)
        opt_drawLogRegression = false;
    end
    if(nargin < 15)
        opt_RegressionDegree = 2;
    end
    if(nargin < 16)
        opt_TexFilenameSuffix = mv;
    end
    if(nargin < 17)
        opt_try_experimental_bound = false;
    end
    if(nargin < 18)
        opt_drawMinMaxPoints = false;
    end
    if(nargin < 19)
        opt_secondaryReversed = false;
    end
    if(nargin < 20)
        opt_ignoreEdgeValues = false;
    end
    if(opt_drawRegressionLine)
        opt_drawLogRegression = false;
    end
    if(opt_drawLogRegression)
        opt_drawRegressionLine = false;
    end
  
%% main graph drawing
    first = 1;
    for testnum = 1:size(tests)
        filename = strcat('SimulationData.', num2str(algoversion), '.Test.', num2str(tests(testnum)), '.mat');
        load(strcat(data_dir, filename)); %#ok<*LOAD>

        ns = GetVar('ns'); %#ok<NASGU>
        ms = GetVar('ms'); %#ok<NASGU>
        ks = GetVar('ks'); %#ok<NASGU>
        if (exist(strcat(eval(strcat('TestName', num2str(tests(testnum)))), 'ones'), 'var') == 1)
            ones = GetVar('ones'); %#ok<NASGU>
        end
        secondary_variable = eval(sv);
        
        if(opt_drawRegressionLine)
            betas = zeros(size(secondary_variable, 1), opt_RegressionDegree + 1);
        else
            betas = zeros(size(secondary_variable, 1), 2);
        end
        colors = zeros(size(secondary_variable, 1), 3);
        
        result_name = extractBetween(sv, 1, strlength(sv) - 1);
        actually_drawn = true(size(first:skip:size(secondary_variable, 1), 2), 1);
        figure;
        hold on;
        for i = first:skip:size(secondary_variable, 1)
            ys = GetVar(sprintf('%s_%d_result', result_name{1}, secondary_variable(i)));
            means = mean(ys, 1)';
            meaningful_indeces = means > 0;
            
            main_variable = eval(mv);
            if(opt_ignoreEdgeValues)
                meaningful_indeces(main_variable > opt_ignoreThreshold * secondary_variable(i)) = false;
            end
            
            if (~any(meaningful_indeces(opt_IgnoreFirst + 1:end)))
                actually_drawn(i) = false;
                continue;
            end
            if(opt_drawRegressionLine)
                lineH = plot(main_variable(meaningful_indeces), means(meaningful_indeces), '*');
                if(opt_try_experimental_bound)
                    % calculate UPPER bound and draw it
                    % cycle_length_constant = 8; note also 3 and 2 !!!
                    experimental_times = 1 / ks * (8 * 3 * secondary_variable(i) * main_variable(meaningful_indeces) .^ 2 + ...
                        8 * main_variable(meaningful_indeces) * secondary_variable(i) ^ 2 + ...
                        + 8 * 2 * main_variable(meaningful_indeces) * secondary_variable(i) * (secondary_variable(i) - 1));
                    plot(main_variable(meaningful_indeces), experimental_times, '-.', ...
                        'LineWidth',0.5, 'Color', lineH.Color, 'HandleVisibility','off');
                end
                if(opt_drawMinMaxPoints)
                    maxs = max(ys, [], 1)';
                    mins = min(ys, [], 1)';
                    errorbar(main_variable(meaningful_indeces), means(meaningful_indeces), ...
                        mins(meaningful_indeces), maxs(meaningful_indeces), 'LineStyle', 'none' , ...
                        'LineWidth',0.5, 'Color', lineH.Color, 'HandleVisibility', 'off')
                end
            else
                lineH = plot(main_variable, means);
            end
            colors(i, :) = lineH.Color;
            if(opt_drawRegressionLine)
                draw_ind = (1:size(meaningful_indeces, 1))';
                draw_ind = meaningful_indeces & (draw_ind > opt_IgnoreFirst);
                if(any(draw_ind))
                    betas(i, :) = DrawLinearRegressionLine(main_variable(draw_ind, :), ys(:, draw_ind), opt_RegressionDegree, colors(i, :));
                end
            end
        end
        hold off;
        title(titleFcn());
        ylabel('Time (seconds)');
        xlabel(xLabelName);
        xlim([main_variable(1+opt_IgnoreFirst) main_variable(end)]);
        legendStr = convertCharsToStrings(sprintf('%s = ', result_name{1})) + num2str(secondary_variable(first:skip:end));
        if(opt_drawRegressionLine)
            varName = extractBetween(mv, 1, strlength(mv) - 1);
            legendStr = legendStr + "; T_{est} = ";
            if(opt_secondaryReversed)
                for deg=opt_RegressionDegree:-1:2
                    legendStr = legendStr + num2str(betas(first:skip:end, deg + 1) .* secondary_variable(first:skip:end), '%.3f') + ...
                        " \cdot \tfrac{1}{" + result_name{1} + "} \cdot " + varName + "^" + num2str(deg) + " + ";
                end
            else
                for deg=opt_RegressionDegree:-1:2
                    legendStr = legendStr + num2str(betas(first:skip:end, deg + 1) ./ secondary_variable(first:skip:end), '%.3f') + ...
                        "\cdot" + result_name{1} + "\cdot" + varName + "^" + num2str(deg) + " + ";
                end
            end
            if(opt_RegressionDegree == 1)
                legendStr = legendStr + num2str(betas(first:skip:end, 2), '%.1f') + varName + " + O(1)";
            else
                legendStr = legendStr + "O(" + varName + ")";
            end
        end
        
        legend(cellstr(legendStr(actually_drawn)), 'Location', normPlotLegLocation);

        PrintToLatex(printToLatex, data_dir, ...
            strcat('Matlab.Data.', num2str(algoversion), '.', num2str(tests(testnum)), '.', opt_TexFilenameSuffix));

        if (opt_drawLogRegression)
            figure;
            hold on;
            for i = first:skip:size(secondary_variable, 1)
                ys = GetVar(sprintf('%s_%d_result', result_name{1}, secondary_variable(i)));
                means = mean(ys, 1)';
                stds = std(ys)';
                main_variable = eval(mv);
                errorbar(main_variable, means, stds, 'vertical', 's','MarkerSize',4, 'Color', colors(i, :));
                betas(i, :) = DrawBestFitLogLine(...
                    main_variable(1 + opt_IgnoreFirst:end), ...
                    ys(:, 1 + opt_IgnoreFirst:end), ...
                    colors(i, :));
            end
            hold off;
            set(gca,'xscale','log')
            set(gca,'yscale','log')
            title(titleFcn());
            ylabel('Time (seconds)');
            xlabel(xLabelName);
            xlim([main_variable(1) main_variable(end)]);
            legend(cellstr(...
                convertCharsToStrings(sprintf('%s = ', result_name{1})) + num2str(secondary_variable(first:skip:end)) + ...
                "; \beta = " + num2str(betas(first:skip:end, 2), '%.3f')), ...
                'Location', logPlotLegLocation);

            PrintToLatex(printToLatex, data_dir, ...
                strcat('Matlab.Data.', num2str(algoversion), '.', num2str(tests(testnum)), '.', opt_TexFilenameSuffix, '.Power'));
        end
    end
end

function [] = DrawGraphs_k(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ks', 'ns', 1, ...
        evalin('caller', 'printToLatex'), ...
        'N_0', ...
        @() sprintf('Average ticks until solution as a function of N_0. On n \\times %d grid', evalin('caller', 'ms')), ...
        'northeast', ...
        'northeast' ...
        , 0 ...
        , false ...
        , true ...
        );
end

function [] = DrawGraphs_m(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ms', 'ns', 1, ...
        evalin('caller', 'printToLatex'), ...
        'm (column number)', ...
        @() sprintf('Average ticks until solution as a function of m. On n \\times m grid. (k = %d)', evalin('caller', 'ks')), ...
        'northwest', ...
        'northwest' ...
        , 0 ...
        , true ...
        );

end

function [] = DrawGraphs_m_mm(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ms', 'ns', 5, ...
        evalin('caller', 'printToLatex'), ...
        'm (column number)', ...
        @() sprintf('Average ticks until solution as a function of m. On n \\times m grid. (k = %d)', evalin('caller', 'ks')), ...
        'northwest', ...
        'northwest' ...
        , 0 ...
        , true ...
        , false ...
        , 2 ...
        , 'ms' ...
        , true ...
        , true ...
        );

end


function [] = DrawGraphs_n(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ns', 'ms', 1, ...
        evalin('caller', 'printToLatex'), ...
        'n (row number)', ...
        @() sprintf('Average ticks until solution as a function of n. On n \\times m grid. (k = %d)', evalin('caller', 'ks')), ...
        'northwest', ...
        'southeast' ...
        , 0 ...
        , true ...
        );
end

function [] = DrawGraphs_n_on_k(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ns', 'ks', 1, ...
        evalin('caller', 'printToLatex'), ...
        'n (row number)', ...
        @() 'Average ticks until solution as a function of n. On n \\times 2 grid.', ...
        'northwest', ...
        'southeast' ...
        , 0 ...
        , true ...
        , false ...
        , 2 ...
        , 'ns' ...
        , false ...
        , false ...
        , true ...
        );
end

function [] = DrawGraphs_n_mm(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ns', 'ms', 5, ...
        evalin('caller', 'printToLatex'), ...
        'n (row number)', ...
        @() sprintf('Average ticks until solution as a function of n. On n \\times m grid. (k = %d)', evalin('caller', 'ks')), ...
        'northwest', ...
        'southeast' ...
        , 0 ...
        , true ...
        , false ...
        , 2 ...
        , 'ns' ...
        , true ...
        , true ...
        );
end

function [] = DrawGraphs_ones(tests, skips, ignoreFirst, highestDegree) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ones', 'ns', skips, ...
        evalin('caller', 'printToLatex'), ...
        'N_1 (exiting vehicle number)', ...
        @() sprintf('Average ticks until solution as a function of N_1. On n \\times %d grid. (k = %d)', evalin('caller', 'ms'), evalin('caller', 'ks')), ...
        'southeast', ...
        'southeast', ...
        ignoreFirst, ...
        true, ...
        false, ...
        highestDegree, ...
        'N1' ...
        , false ...
        , false ...
        , false ...
        , true ...
        , 0.85 ...        
        );
    
end

function [] = DrawGraphs_FreeRoad_m(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ms', 'ns', 2, ...
        evalin('caller', 'printToLatex'), ...
        'm (column number)', ...
        @() sprintf('Average ticks until solution as a function of m. On n \\times m grid. (free slots = %0.2f)', evalin('caller', 'GetVar(''freeRatio'')')), ...
        'northwest', ...
        'southeast' ...
        , 0 ...
        , true ...
        , false ...
        , 1 ...
        );

end

function [] = DrawGraphs_FreeRoad_n(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ns', 'ms', 1, ...
        evalin('caller', 'printToLatex'), ...
        'n (row number)', ...
        @() sprintf('Average ticks until solution as a function of n. On n \\times m grid. (free slots = %0.2f)', evalin('caller', 'GetVar(''freeRatio'')')), ...
        'northwest', ...
        'southeast' ...
        , 0 ...
        , true ...
        , false ...
        , 1 ...
        );
end

function [] = DrawGraphs_FreeRoad_n_on_k(tests) %#ok<DEFNU>
    DrawGraphs_Common(tests, ...
        evalin('caller', 'algoversion'), ...
        evalin('caller', 'data_dir'), ...
        'ns', 'ones', 1, ...
        evalin('caller', 'printToLatex'), ...
        'n (row number)', ...
        @() sprintf('Average ticks until solution as a function of n. On n \\times m grid. (free slots = %0.2f)', evalin('caller', 'GetVar(''freeRatio'')')), ...
        'northwest', ...
        'southeast' ...
        , 0 ...
        , true ...
        , false ...
        , 1 ...
        );
end

function [] = DrawGraphs_Algos(tests) %#ok<DEFNU>
    for testnum = 1:size(tests, 1)
        filename = strcat('SimulationData.Algos.Test.', num2str(tests(testnum)), '.mat');

        load(strcat(evalin('caller', 'data_dir'), filename));

        ns = GetVar('ns');
        m = GetVar('ms'); %#ok<NASGU>
        k = GetVar('ks');
        algorithmVersions = GetVar('AlgorithmVersions');
        
        betas = zeros(size(algorithmVersions, 1), 2);
        colors = zeros(size(algorithmVersions, 1), 3);        

        figure;
        hold on;
        for algo = 1:size(algorithmVersions, 1)
            ys = GetVar(sprintf('algo_%d_result', algorithmVersions(algo)));
            means = mean(ys, 1)';
            lineH = plot(ns, means);
            colors(algo, :) = lineH.Color;
        end
        hold off;
        title(sprintf('Average ticks until solution as a function of n. On n \\times m grid. (k = %d)', k));
        ylabel('Time');
        xlabel('n (number rows)');
        xlim([ns(1) ns(end)]);
        legend(cellstr(strcat('algo ver. = ', num2str(algorithmVersions))), 'Location', 'northwest');

        figure;
        hold on;
        for algo = 1:size(algorithmVersions, 1)
            ys = GetVar(sprintf('algo_%d_result', algorithmVersions(algo)));
            means = mean(ys, 1)';
            stds = std(ys)';
            errorbar(ns, means, stds, 'vertical', 's','MarkerSize',4, 'Color', colors(algo, :));
            betas(algo, :) = DrawBestFitLogLine(ns, ys, colors(algo, :));
        end
        hold off;
        set(gca,'xscale','log')
        set(gca,'yscale','log')
        title(sprintf('Average ticks until solution as a function of n. On n \\times m grid. (k = %d)', k));
        ylabel('Time');
        xlabel('n (number rows)');
        xlim([ns(1) ns(end)]);
        legend(cellstr("algo ver. = " + num2str(algorithmVersions)) + ...
            "; \beta = " + num2str(betas(:, 2), '%.3f'), 'Location', 'southeast');
    end
end


function [beta] = DrawBestFitLogLine(xs, ys, color)
    log_ys = log10(ys);

    means = zeros(size(ys, 2), 1);
    stds = zeros(size(ys, 2), 1);
    for i=1:size(ys, 2)
        take_elements = log_ys(:, i) > 0;
        means(i) = mean(log_ys(take_elements, i));
        stds(i) = std(log_ys(take_elements, i));
    end
    
    W = diag(1 ./ (stds .^ 2));
    X = [ones(size(xs)), log10(xs)];
    beta = (X' * W * X) \ (X' * W * means);
    plot(xs, 10 .^ ([ones(size(xs)), log10(xs)] * beta), 'Color', color, 'HandleVisibility','off');
end

function [beta] = DrawLinearRegressionLine(xs, ys, highestDegree, color)
    means = mean(ys, 1)';
    
    X = ones(size(xs, 1), highestDegree + 1);
    for deg=1:highestDegree
        X(:, deg + 1) = xs .^ deg;
    end
    beta = (X' * X) \ (X' * means);
    plot(xs, X * beta, '--', 'Color', color, 'HandleVisibility','off');
end


function [] = PrintToLatex(printToLatex, data_dir, filename)
    %cleanfigure;
    if(printToLatex)
        matlab2tikz(strcat(data_dir, filename, '.tex'));
    end
end

function variable = GetVar(name)
    tests = evalin('caller', 'tests');
    testnum = evalin('caller', 'testnum');
    variable = evalin('caller', strcat(evalin('caller', strcat('TestName', num2str(tests(testnum)))), name));
end