classdef StateMachine < Cylinders.StateMachine.TimerStateMachine
    %STATEMACHINE Actual Implementation of Sorting algorithm
    % works on TWO COLUMNS !
    %
    % This is a SORTING algorithm for 1's [CONTINUING vehicles]
    %
    % Ver = 319 (1 for exiting, 2 for continuing)
    %
    % 2 bit timer [LSB bits] - 00 LEFT column NE, 01 LEFT column ES, 10 RIGHT column SW, 11 RIGHT column NW
    % 1 bit state : 0 - going up, 1 - going down 
    
    properties (Constant)
        MasksVersion = 202009072;
        TimerBits = 2;
        ValueBits = 1;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            up___direction = 0;
            down_direction = 1;
            

            %% here comes position 1
            % please check that readings are [west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ... % NOTE, go_west is useless at 11 !! + position 4 and 8
                        % not really only if in up_direction (i.e. stayed in position 1 at 10
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ... % go_west
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ... % go_west
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
                        this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ... % NOTE
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ... % here, if did not go West at 10, then no need to try at 11
                        % since you can't get to position 4 at time 10 !!!!
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ... % go_west
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ... % go_west
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                         }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                         }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ... % after going South at 10 you still can get to position 8 at 11 against an
                        % empty space
                        {[empty, empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ... % go_west
                                    }}, ...
                        {[empty, empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ... % go_west
                                    }}, ...
                        {[empty, agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ... % go_west
                                    }}, ...
                        {[agent, empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ...
                                        Cylinders.StateMachine.Action(up___direction, go_west), ... % go_west
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ...
                                        Cylinders.StateMachine.Action(down_direction, go_west), ... % go_west
                                    }}, ...
                        {[agent, agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south, west]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                         }}, ...
                } ...                
            );
        end
    end
end

