classdef StateMachine < Cylinders.StateMachine.TimerStateMachine
    %STATEMACHINE Actual Implementation of Sorting algorithm
    % works on AT LEAST THREE COLUMNS !
    %
    % Based on covering algorithm Ver 9
    % This is a SORTING algorithm for 1's [CONTINUING vehicles]
    %
    % Ver = 311 (1 for exiting, 2 for continuing)
    %
    % 2 bit timer [LSB bits] - 00 and 01 are times at which COVERING algo is executed; 10 is the Pos 9 exiting vehicles moving  east; 11 - Pos 8
    % continuing vehicles moving west
    % 2 bit state : COVERING Algorithm direction + 1 bit in Position 8 to count passing empty cells
    
    properties (Constant)
        MasksVersion = 20200830;
        TimerBits = 2;
        ValueBits = 2;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            main_direction = 0;
            secondary_direction = 1;
            empty_cell_not_passed = main_direction;
            empty_cell_passed = 1;
            empty_cell_passed_twice = 2;
            

            %% here comes position 1
            % please check that readings are [west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {empty, { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                    {agent,	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                    {[empty, agent], { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                    {[agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ... 
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            % please check that readings are [north] only
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            % please check that readings are [east, south]
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, go_south), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, go_south), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 8
            % please check that readings are [west, south]
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty]        ...
                                    {   ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, go_south), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, go_south), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, go_south), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, go_west), ...
                                    }}, ...
                        {[empty, agent]        ...
                                    {   ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, go_west), ...
                                    }}, ...
                        {[agent, empty]        ...
                                    {   ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, go_south), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, go_south), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, go_south), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                    }}, ...
                        {[agent, agent]        ...
                                    {   ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_not_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                        Cylinders.StateMachine.Action(empty_cell_passed_twice, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, go_south), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                    {[empty, agent], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                    {[agent, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, go_south), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                    {[agent, agent], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(secondary_direction, do_nothing), ...
                                     }}, ...
                } ...                
            );
        end
    end
end

