classdef StateMachine < Cylinders.StateMachine.GenericStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    %
    % one bit to conceptualize column traversing in both directions
    % second bit is to conceptualize row traversing in east-west direction
    
    properties (Constant)
        MasksVersion = 20200610;
        TimerBits = 0;
        ValueBits = 2;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            main_direction = 0;
            traverse_north = 1;
            traverse_west = 2;
            traverse_east = 3;
            

            %% here comes position 1
            % please check that readings are [north]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {empty, { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... dead
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(traverse_west, go_west), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... dead
                                        Cylinders.StateMachine.Action(traverse_east, go_east), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(traverse_north, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... dead
                                        Cylinders.StateMachine.Action(traverse_west, go_west), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(traverse_north, go_south), ...
                                        Cylinders.StateMachine.Action(traverse_west, go_west), ...
                                        Cylinders.StateMachine.Action(traverse_east, go_east), ...
                                     }}, ...
                } ...                
            );
        end
    end
end

