classdef StateMachine < Cylinders.StateMachine.GenericStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    %
    % one conceptual bit of time parity (to prevent possible collisions) and one of direction up/down
    % all except 1, 5, 9 ,could move anytime; former north+west at odd times, and down at even
    % in this specific implementation LEAST SIGNIFICANT BIT is the timer !!
    % visibility of 1
    % NOT WORKING: some agents stuck exactly cause empty spaces are going through position 7 !!
    
    properties (Constant)
        MasksVersion = 20200407;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            wall = Cylinders.Visibility.Constants.Wall;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;
            
            %% here comes position 1
            % please check that readings are [west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty], { ... % check out that 2 is impossible memory state at poisiton 5
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, go_west), ...
                                     }}, ...
                    {[agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                     }}, ...
                } ...                
            );
            
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(1, go_north), ...
                                        Cylinders.StateMachine.Action(0, go_north), ...
                                        Cylinders.StateMachine.Action(1, go_north), ... % only for state 2
                                        Cylinders.StateMachine.Action(0, go_north), ... % only for state 2
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(1, go_east), ...
                                        Cylinders.StateMachine.Action(0, go_east), ...
                                        Cylinders.StateMachine.Action(1, go_south), ... % for state 7
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(1, go_south), ... % for state 7
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(1, go_south), ...
                                        Cylinders.StateMachine.Action(0, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, agent], { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, go_west), ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                     }}, ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, go_west), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, go_north), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                     }}, ...
                    {[agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, go_north), ... 
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            %% here comes position 7
            %% here comes position 8
            for currentPosition = 6:8
                this.stateMachine{currentPosition} = this.stateMachine{currentPosition - 4};
            end
            %% here comes position 9
            % please check that readings are [north, south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ...
                                        Cylinders.StateMachine.Action(1, go_south), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, go_north), ...
                                     }}, ...
                    {[agent, empty], { ... 
                                        Cylinders.StateMachine.Action(1, go_south), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ...
                                     }}, ...
                    {[empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, go_north), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ...
                                     }}, ...
                } ...                
            );
        end
    end
end

