classdef StateMachine < Cylinders.StateMachine.TimerStateMachine
    %STATEMACHINE Actual Implementation of Sorting algorithm
    % works on TWO COLUMNS !
    %
    % This is a SORTING algorithm for 1's [EXITING vehicles]
    %
    % Ver = 319 (1 for exiting, 2 for continuing)
    %
    % 2 bit timer [LSB bits] - 00 LEFT column NE, 01 LEFT column ES, 10 RIGHT column SW, 11 RIGHT column NW
    % 1 bit state : 0 - going up, 1 - going down 
    %
    % FIXING inconsistences in 317/318
    % 1. No D-bit change, if no empty neighbors (pos 6 and 8) ?
    % 2. D-bit changes WHEN you should have left in the "rival" state
    
    properties (Constant)
        MasksVersion = 202009071;
        TimerBits = 2;
        ValueBits = 1;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            up___direction = 0;
            down_direction = 1;
            

            %% here comes position 1
            % please check that readings are [west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {empty, { ... 
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, go_north), ...
                                Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                             }}, ...
                    {agent, { ... 
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                             }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ... % NOTE, go_east is useless at 01 !!
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ... %go_east
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ... %go_east
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ... %go_east
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ... %go_east
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                         }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, go_east), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, go_east), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                         }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {[empty, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[empty, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, go_north), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, empty],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, go_south), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                    }}, ...
                        {[agent, agent],         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(down_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(up___direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south, west]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                         }}, ...
                } ...                
            );
        end
    end
end

