classdef StateMachine < Cylinders.StateMachine.GenericStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    
    properties (Constant)
        MasksVersion = 20200324;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            wall = Cylinders.Visibility.Constants.Wall;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;
            Error = Cylinders.Visibility.Constants.Error;
            Unspecified = Cylinders.Visibility.Constants.Unspecified;
            
            %% here comes position 1
            % please check that readings are [west_north, west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                     }}, ...
                    {[agent, empty], { ... % small optimization could be done here, if near 2 ! same in position 5
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                     }}, ...
                    {[empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                     }}, ...
                } ...                
            );
            
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.MultiRowState({ ...
                Cylinders.StateMachine.State(masks.MaskPosition(currentPosition), ... % memory = 0 ...
                    { ...
                        {empty,     Cylinders.StateMachine.Action(0, go_north)}; ...
                        {agent,     Cylinders.StateMachine.Action(0, do_nothing)}; ...
                    }) ...
                });
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.MultiRowState({ ...
                Cylinders.StateMachine.State(masks.MaskPosition(currentPosition), ... % memory = 0 ...
                    { ...
                        {empty,     Cylinders.StateMachine.Action(0, go_east)}; ...
                        {agent,     Cylinders.StateMachine.Action(0, do_nothing)}; ...
                    }) ...
                });
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.MultiRowState({ ...
                Cylinders.StateMachine.State(masks.MaskPosition(currentPosition), ... % memory = 0 ...
                    { ...
                        {empty,     Cylinders.StateMachine.Action(0, go_south)}; ...
                        {agent,     Cylinders.StateMachine.Action(0, do_nothing)}; ...
                    }) ...
                });
            %% here comes position 5
            % please check that readings are [west_north, west, north_north, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty, Unspecified, agent], { ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                     }}, ...
                    {[empty, empty, empty, empty], { ... 
                                        Cylinders.StateMachine.Action(1, go_north), ...
                                        Cylinders.StateMachine.Action(1, go_north), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                     }}, ...
                    {[empty, empty, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(1, go_north), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                     }}, ...
                    {[agent, empty, Unspecified, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                     }}, ...
                    {[agent, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                     }}, ...
                    {[agent, empty, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(0, go_west), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                     }}, ...
                    {[empty, agent, Unspecified, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                     }}, ...
                    {[agent, agent, Unspecified, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                     }}, ...
                    {[empty, agent, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ... 
                                     }}, ...
                    {[empty, agent, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ... 
                                     }}, ...
                    {[agent, agent, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, do_nothing), ... 
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ... 
                                     }}, ...
                    {[agent, agent, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(1, go_north), ... 
                                        Cylinders.StateMachine.Action(3, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, do_nothing), ... 
                                     }}, ...
                    {[empty, empty, wall, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_west), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, Error), ...
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                    {[agent, empty, wall, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_west), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, go_west), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                    {[empty, agent, wall, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, Error), ...
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                    {[agent, agent, wall, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, Error), ...
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            %% here comes position 7
            %% here comes position 8
            for currentPosition = 6:8
                this.stateMachine{currentPosition} = this.stateMachine{currentPosition - 4};
            end
            %% here comes position 9
            % please check that readings are [north_north, north, south, south_south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = Cylinders.StateMachine.GenericStateMachine.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[Unspecified, agent, agent, Unspecified], { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                     }}, ...
                    {[agent, empty, agent, Unspecified], { ... 
                                        Cylinders.StateMachine.Action(1, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, go_north), ...
                                        Cylinders.StateMachine.Action(3, go_north), ...
                                        Cylinders.StateMachine.Action(0, Error), ...
                                     }}, ...
                    {[wall, empty, agent, Unspecified],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                     }}, ...
                    {[empty, empty, agent, Unspecified],	...
                                     { ...
                                        Cylinders.StateMachine.Action(2, go_north), ...
                                        Cylinders.StateMachine.Action(2, go_north), ...
                                        Cylinders.StateMachine.Action(2, go_north), ...
                                        Cylinders.StateMachine.Action(0, Error), ...
                                     }}, ...
                    {[Unspecified, agent, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                     }}, ...
                    {[agent, empty, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(3, go_north), ... 
                                     }}, ...
                    {[wall, empty, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                     }}, ...
                    {[empty, empty, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(2, go_north), ...
                                        Cylinders.StateMachine.Action(3, go_north), ... 
                                     }}, ...
                    {[Unspecified, agent, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(3, go_south), ... 
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                    {[agent, empty, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(3, go_south), ... 
                                        Cylinders.StateMachine.Action(2, do_nothing), ... 
                                        Cylinders.StateMachine.Action(2, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                    {[wall, empty, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(3, go_south), ... 
                                        Cylinders.StateMachine.Action(3, go_south), ... 
                                        Cylinders.StateMachine.Action(0, do_nothing), ...
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                    {[empty, empty, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(3, go_south), ... 
                                        Cylinders.StateMachine.Action(3, go_south), ... 
                                        Cylinders.StateMachine.Action(3, go_south), ...
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                     }}, ...
                    {[Unspecified, agent, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                     }}, ...
                    {[agent, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                     }}, ...
                    {[wall, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                     }}, ...
                    {[empty, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                        Cylinders.StateMachine.Action(0, Error), ... 
                                        Cylinders.StateMachine.Action(0, go_south), ...
                                        Cylinders.StateMachine.Action(0, go_south), ... 
                                     }}, ...
                } ...                
            );
        end
    end
end

