classdef StateMachine < Cylinders.StateMachine.TimerStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    %
    % one conceptual bit of time parity (to prevent possible collisions) and one of direction up/down
    % all except 1, 5, 9 ,could move anytime; former north+west at ODD times, and down at EVEN
    % in this specific implementation LEAST SIGNIFICANT BIT is the timer !!
    % and MOST SIGNIFICANT BIT is a direction (0 - NW, 1 - S)
    
    properties (Constant)
        MasksVersion = 20200324;
        TimerBits = 1;
        ValueBits = 1;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            wall = Cylinders.Visibility.Constants.Wall;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;
            Unspecified = Cylinders.Visibility.Constants.Unspecified;
            
            main_direction = 0;
            south_9_west_5_direction = 1;
            
            %% here comes position 1
            % please check that readings are [west_north, west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... % check out that 2 is impossible memory state at poisiton 5
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                     }}, ...
                    {[agent, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                     }}, ...
                    {[empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west_north, west, north_north, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty, Unspecified, agent], { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                     }}, ...
                    {[empty, empty, empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                     }}, ...
                    {[empty, empty, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ...
                                     }}, ...
                    {[agent, empty, Unspecified, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ... 
                                     }}, ...
                    {[agent, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ... 
                                     }}, ...
                    {[agent, empty, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ... 
                                     }}, ...
                    {[empty, agent, Unspecified, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[agent, agent, Unspecified, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                     }}, ...
                    {[empty, agent, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[empty, agent, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[agent, agent, agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[agent, agent, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                     }}, ...
                    {[empty, empty, wall, empty],	...%
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_west), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ... 
                                     }}, ...
                    {[agent, empty, wall, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_west), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_west), ... 
                                     }}, ...
                    {[empty, agent, wall, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[agent, agent, wall, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            %% here comes position 7
            %% here comes position 8
            for currentPosition = 6:8
                this.stateMachine{currentPosition} = this.stateMachine{currentPosition - 4};
            end
            %% here comes position 9
            % please check that readings are [north_north, north, south, south_south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[Unspecified, agent, agent, Unspecified], { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                     }}, ...
                    {[agent, empty, agent, Unspecified], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                     }}, ...
                    {[wall, empty, agent, Unspecified],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                     }}, ...
                    {[empty, empty, agent, Unspecified],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ...
                                     }}, ...
                    {[Unspecified, agent, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[agent, empty, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[wall, empty, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[empty, empty, empty, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[Unspecified, agent, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[agent, empty, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[wall, empty, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[empty, empty, empty, wall],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[Unspecified, agent, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[agent, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[wall, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                    {[empty, empty, empty, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ... 
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, go_south), ...
                                        Cylinders.StateMachine.Action(south_9_west_5_direction, do_nothing), ... 
                                     }}, ...
                } ...                
            );
        end
    end
end

