classdef StateMachine < Cylinders.StateMachine.TimerStateMachine
    %STATEMACHINE Actual Implementation of Sorting algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS ! [Need to check]
    %
    % Based on covering algorithm Ver 9
    % This is a SORTING algorithm for 1's [EXITING vehicles]
    %
    % Ver = 307 (1 for exiting, 2 for continuing)
    %
    % 2 bit timer [LSB bits] - 00 and 01 are times at which COVERING algo is executed; 10 is the Pos 9 exiting vehicles moving  east; 11 - Pos 8
    % continuing vehicles moving west
    % 1 bit state : non-MSB bit - is the state bit for COVERING algo; 
    
    properties (Constant)
        MasksVersion = 20200906;
        TimerBits = 2;
        ValueBits = 1;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            main_direction = 0;
            north_9_north_5 = 1;
            

            %% here comes position 1
            % please check that readings are [west]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[empty, agent], { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, empty],	...
                                     { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ... 
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                        {agent,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south, west]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty, empty], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                     }}, ...
                    {[empty, empty, agent], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[empty, agent, empty], { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                     }}, ...
                    {[empty, agent, agent], { ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                     }}, ...
                    {[agent, empty, agent], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                    {[agent, agent, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                     }}, ...
                    {[agent, agent, agent],	...
                                     { ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(main_direction, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, do_nothing), ...
                                     }}, ...
                } ...                
            );
        end
    end
end

