classdef StateMachine < Cylinders.StateMachine.GenericStateMachine
    %STATEMACHINE Actual Implementation of (Motor) Cylinders algorithm
    % works on AT LEAST TWO ROWS and TWO COLUMNS !
    %
    % one of direction up/down 1 is the bit value to move north in 5,9; 0 - to move south and west
    % two other values are used to decide on the wavvy movement in the first/second row
    % This is a primal problem! the sole agent will patrol the grid
    
    properties (Constant)
        MasksVersion = 20200610;
        TimerBits = 0;
        ValueBits = 2;
    end

    methods (Access = protected)
        function [] = InitStateMachines(this)
            masks = this.InitCommonRecords();
            
            %% temporal constants
            empty = Cylinders.Visibility.Constants.Empty;
            agent = Cylinders.Visibility.Constants.Agent;
            go_north = Cylinders.Visibility.Constants.go_north;
            go_east = Cylinders.Visibility.Constants.go_east;
            go_south = Cylinders.Visibility.Constants.go_south;
            go_west = Cylinders.Visibility.Constants.go_west;
            do_nothing = Cylinders.Visibility.Constants.do_nothing;

            main_direction = 0;
            north_9_north_5 = 1;
            wave_west = 2;
            wave_column = 3;
            

            %% here comes position 1
            % please check that readings are [north]
            currentPosition = 1;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {empty, { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 2
            currentPosition = 2;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ... dead
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(wave_column, go_north), ... in case of two rows
                                    }}, ...
                } ...                
            );
            %% here comes position 3
            currentPosition = 3;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ... init only
                                        Cylinders.StateMachine.Action(main_direction, go_south), ... seems dead
                                        Cylinders.StateMachine.Action(main_direction, go_south), ... seems dead
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 4
            currentPosition = 4;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(wave_column, go_west), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 5
            % please check that readings are [west, north]
            currentPosition = 5;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ... 
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(main_direction, go_east), ...
                                        Cylinders.StateMachine.Action(wave_column, go_west), ...
                                        Cylinders.StateMachine.Action(wave_west, go_north), ...
                                     }}, ...
                } ...                
            );
            %% here comes position 6
            currentPosition = 6;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ...
                                        Cylinders.StateMachine.Action(main_direction, go_south), ... dead
                                        Cylinders.StateMachine.Action(main_direction, go_south), ... dead
                                        Cylinders.StateMachine.Action(wave_column, go_north), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 7
            currentPosition = 7;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_south), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_west), ...
                                        Cylinders.StateMachine.Action(wave_column, go_west), ...
                                        Cylinders.StateMachine.Action(wave_west, go_south), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 8
            currentPosition = 8;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                        {empty,         ...
                                    {   ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                    }}, ...
                } ...                
            );
            %% here comes position 9
            % please check that readings are [north, south]
            currentPosition = 9;
            this.stateMachine{currentPosition} = this.CreateStateMachine(masks, currentPosition, ...
                { ...
                    {[empty, empty], { ...
                                        Cylinders.StateMachine.Action(main_direction, go_north), ...
                                        Cylinders.StateMachine.Action(north_9_north_5, go_south), ...
                                        Cylinders.StateMachine.Action(wave_column, go_west), ...
                                        Cylinders.StateMachine.Action(wave_west, go_north), ...
                                     }}, ...
                } ...                
            );
        end
    end
end

